In [1]:
import pandas as pd
import json

df = pd.read_json('../data/dataset-telecon.json')

In [2]:
df.head()

,id_cliente,Churn,cliente,telefone,internet,conta
0,0002-ORFBO,nao,"{'genero': 'feminino', 'idoso': 0, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': None, 'faturamente_eletronico': N..."
1,0003-MKNFE,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': 'mes a mes', 'faturamente_eletron..."
2,0004-TLHLJ,sim,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
3,0011-IGKFF,sim,"{'genero': 'masculino', 'idoso': 1, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
4,0013-EXCHZ,sim,"{'genero': 'feminino', 'idoso': 1, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  7344 non-null   str
 1   Churn       7344 non-null   str
 2   cliente     7344 non-null   object
 3   telefone    7344 non-null   object
 4   internet    7344 non-null   object
 5   conta       7344 non-null   object
dtypes: object(4), str(2)
memory usage: 344.4+ KB

## Normalizando colunas com formato JSON

In [4]:
with open('../data/dataset-telecon.json') as f:
    json_raw = json.load(f)
    
data_normalized = pd.json_normalize(json_raw)
data_normalized.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,NaN,NaN,NaN,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.4
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.4

In [5]:
data_normalized.info()

<class 'pandas.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   str
 1   Churn                          7344 non-null   str
 2   cliente.genero                 7344 non-null   str
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   str
 5   cliente.dependentes            7344 non-null   str
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   str
 8   telefone.varias_linhas         7344 non-null   str
 9   internet.servico_internet      7344 non-null   str
 10  internet.seguranca_online      7344 non-null   str
 11  internet.backup_online         7344 non-null   str
 12  internet.protecao_dispositivo  7344 non-null   str
 13  internet.suporte_tecnico       7344 non-null   str
 14  internet.tv_streaming          7344 non-null   str
 15  internet.filmes_streaming      7344 non-null   str
 16  conta.contrato                 7312 non-null   str
 17  conta.faturamente_eletronico   7326 non-null   str
 18  conta.metodo_pagamento         7317 non-null   str
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   str
dtypes: float64(2), int64(1), str(18)
memory usage: 1.2 MB

In [6]:
#data_normalized['conta.cobranca.Total'] = data_normalized['conta.cobranca.Total'].astype(float){}
#data_normalized[data_normalized['conta.cobranca.Total'] == ' '].head()
data_normalized['conta.cobranca.Total'] = data_normalized['conta.cobranca.Total'].astype(object)
data_normalized[data_normalized['conta.cobranca.Total'] == ' '][['cliente.tempo_servico','conta.contrato','conta.cobranca.mensal', 'conta.cobranca.Total']]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,0.0,dois anos,56.05,
1775,0.0,dois anos,20.00,
1955,0.0,dois anos,61.90,
2075,0.0,dois anos,19.70,
2232,0.0,dois anos,20.25,
2308,0.0,dois anos,25.35,
2930,0.0,dois anos,73.35,
3134,0.0,dois anos,25.75,
3203,0.0,dois anos,52.55,
4169,0.0,dois anos,80.85,
5599,0.0,dois anos,19.85,

In [7]:
idx = data_normalized[data_normalized['conta.cobranca.Total'] == ' '].index
data_normalized.loc[idx, 'cliente.tempo_servico'] = 24
data_normalized.loc[idx, 'conta.cobranca.Total'] = data_normalized.loc[idx,'cliente.tempo_servico'] * data_normalized.loc[idx,'conta.cobranca.mensal']
data_normalized.loc[idx, ['cliente.tempo_servico','conta.contrato','conta.cobranca.mensal', 'conta.cobranca.Total']]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,24.0,dois anos,56.05,1345.2
1775,24.0,dois anos,20.00,480.0
1955,24.0,dois anos,61.90,1485.6
2075,24.0,dois anos,19.70,472.8
2232,24.0,dois anos,20.25,486.0
2308,24.0,dois anos,25.35,608.4
2930,24.0,dois anos,73.35,1760.4
3134,24.0,dois anos,25.75,618.0
3203,24.0,dois anos,52.55,1261.2
4169,24.0,dois anos,80.85,1940.4
5599,24.0,dois anos,19.85,476.4

In [8]:
data_normalized['conta.cobranca.Total'] = data_normalized['conta.cobranca.Total'].astype(float)

# Identificando e tratando strings vazias

In [9]:
for col in data_normalized.columns:
    print(f'Coluna: {col}')
    print(data_normalized[col].unique())
    print('-' * 30)

Coluna: id_cliente
<StringArray>
['0002-ORFBO', '0003-MKNFE', '0004-TLHLJ', '0011-IGKFF', '0013-EXCHZ',
 '0013-MHZWF', '0013-SMEOE', '0014-BMAQU', '0015-UOCOJ', '0016-QLJIS',
 ...
 '9975-SKRNR', '9978-HYCIN', '9979-RGMZT', '9985-MWVIX', '9986-BONCE',
 '9987-LUTYD', '9992-RRAMN', '9992-UJOEL', '9993-LHIEB', '9995-HOTOH']
Length: 7267, dtype: str
------------------------------
Coluna: Churn
<StringArray>
['nao', 'sim', '']
Length: 3, dtype: str
------------------------------
Coluna: cliente.genero
<StringArray>
['feminino', 'masculino']
Length: 2, dtype: str
------------------------------
Coluna: cliente.idoso
[0 1]
------------------------------
Coluna: cliente.parceiro
<StringArray>
['sim', 'nao']
Length: 2, dtype: str
------------------------------
Coluna: cliente.dependentes
<StringArray>
['sim', 'nao']
Length: 2, dtype: str
------------------------------
Coluna: cliente.tempo_servico
[9.00e+00 4.00e+00 1.30e+01 3.00e+00 7.10e+01 6.30e+01 7.00e+00      nan
 5.40e+01 7.20e+01 5.00e+00 5.60e+01 3.40e+01 1.00e+00 4.50e+01 5.00e+01
 2.30e+01 5.50e+01 2.60e+01 6.90e+01 1.10e+01 3.70e+01 4.90e+01 6.60e+01
 6.70e+01 2.00e+01 4.30e+01 5.90e+01 1.20e+01 2.70e+01 2.00e+00 2.50e+01
 2.90e+01 1.40e+01 3.50e+01 6.40e+01 3.90e+01 4.00e+01 6.00e+00 3.00e+01
 7.00e+01 5.70e+01 5.80e+01 1.60e+01 3.20e+01 3.30e+01 1.00e+01 2.10e+01
 6.10e+01 1.50e+01 4.40e+01 2.20e+01 2.40e+01 1.90e+01 4.70e+01 6.20e+01
 4.60e+01 5.20e+01 8.00e+00 6.00e+01 4.80e+01 2.80e+01 6.50e+01 4.10e+01
 5.30e+01 6.80e+01 5.10e+01 3.10e+01 3.60e+01 1.70e+01 1.80e+01 3.80e+01
 4.20e+01 1.08e+03 1.00e+03 9.50e+02 2.54e+02 3.21e+02 6.50e+02 7.00e+02
 7.21e+02 5.55e+02 4.33e+02 5.12e+02]
------------------------------
Coluna: telefone.servico_telefone
<StringArray>
['sim', 'nao']
Length: 2, dtype: str
------------------------------
Coluna: telefone.varias_linhas
<StringArray>
['nao', 'sim', 'sem servico de telefone']
Length: 3, dtype: str
------------------------------
Coluna: internet.servico_internet
<StringArray>
['DSL', 'fibra otica', 'nao']
Length: 3, dtype: str
------------------------------
Coluna: internet.seguranca_online
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.backup_online
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.protecao_dispositivo
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.suporte_tecnico
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.tv_streaming
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.filmes_streaming
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: conta.contrato
<StringArray>
[nan, 'mes a mes', 'dois anos', 'um ano']
Length: 4, dtype: str
------------------------------
Coluna: conta.faturamente_eletronico
<StringArray>
[nan, 'nao', 'sim']
Length: 3, dtype: str
------------------------------
Coluna: conta.metodo_pagamento
<StringArray>
[                                  nan,                 'cheque pelo correio',
                   'cheque eletronico',      'cartao de credito (automatico)',
 'transferencia bancaria (automatica)']
Length: 5, dtype: str
------------------------------
Coluna: conta.cobranca.mensal
[  nan 59.9  73.9  ... 91.75 68.8  67.85]
------------------------------
Coluna: conta.cobranca.Total
[    nan  542.4   280.85 ...  742.9  4627.65 3707.6 ]
------------------------------

In [10]:
data_normalized.query("Churn == ''")

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
30,0047-ZHDTW,,feminino,0,nao,nao,11.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,transferencia bancaria (automatica),79.00,929.30
75,0120-YZLQA,,masculino,0,nao,nao,71.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cartao de credito (automatico),19.90,1355.10
96,0154-QYHJU,,masculino,0,nao,nao,29.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,um ano,sim,cheque eletronico,58.75,1696.20
98,0162-RZGMZ,,feminino,1,nao,nao,5.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,mes a mes,nao,cartao de credito (automatico),59.90,287.85
175,0274-VVQOQ,,masculino,1,sim,nao,65.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,um ano,sim,transferencia bancaria (automatica),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7211,9920-GNDMB,,masculino,0,nao,nao,9.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,cheque eletronico,76.25,684.85
7239,9955-RVWSC,,feminino,0,sim,sim,67.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,transferencia bancaria (automatica),19.25,1372.90
7247,9966-VYRTZ,,feminino,0,sim,sim,31.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,mes a mes,sim,cheque pelo correio,19.55,658.95
7267,6532-YOHZY,,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,transferencia bancaria (automatica),109.75,4900.65
7342,3601-UTZXO,,masculino,0,sim,sim,41.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,transferencia bancaria (automatica),19.50,798.20

In [11]:
data_normalized = data_normalized[data_normalized['Churn'] != ''].reset_index(drop=True)

In [12]:
data_normalized.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,NaN,NaN,NaN,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40

# Identificando e tratando dados duplicados

In [24]:
#Verificando duplicatas
data_normalized.duplicated().sum()

np.int64(0)

In [ ]:
#Criando um filtro para verificar duplicatas
filter_duplicated = data_normalized.duplicated()
data_normalized[filter_duplicated].head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
7043,0675-NCDYU,nao,feminino,0,sim,sim,72.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,cartao de credito (automatico),116.4,8543.25
7044,6754-LZUKA,nao,masculino,0,sim,nao,61.0,sim,sim,DSL,...,sim,sim,nao,sim,sim,dois anos,nao,transferencia bancaria (automatica),80.9,4932.50
7045,2192-CKRLV,nao,feminino,0,sim,nao,72.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,dois anos,sim,cheque eletronico,49.2,3580.95
7046,9170-ARBTB,nao,feminino,0,sim,sim,52.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),19.6,1012.40
7047,0447-BEMNG,sim,feminino,0,sim,nao,48.0,nao,sem servico de telefone,DSL,...,nao,sim,nao,nao,sim,mes a mes,sim,transferencia bancaria (automatica),45.3,2145.00

In [ ]:
#Removendo duplicatas
data_normalized.drop_duplicates(inplace=True)
data_normalized.duplicated().sum()

np.int64(0)

# Identificando e tratando dados nulos

In [26]:
data_normalized.isna().sum()

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             8
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

In [27]:
data_normalized[data_normalized['cliente.tempo_servico'].isna()][['cliente.tempo_servico','conta.cobranca.mensal', 'conta.cobranca.Total']]

      cliente.tempo_servico  conta.cobranca.mensal  conta.cobranca.Total
9                       NaN                  90.45               5957.90
176                     NaN                  29.30                355.90
181                     NaN                  63.95                318.10
751                     NaN                 101.05               5971.25
3523                    NaN                  76.10               1054.80
5273                    NaN                  20.60                116.60
5276                    NaN                  73.85               3581.40
6134                    NaN                  69.05               1958.45

In [34]:
idx = data_normalized[data_normalized['cliente.tempo_servico'].isna()].index
data_normalized.loc[idx, 'cliente.tempo_servico'] = data_normalized.loc[idx, 'conta.cobranca.Total'] / data_normalized.loc[idx, 'conta.cobranca.mensal'].round()
data_normalized['cliente.tempo_servico'].isna().sum()

np.int64(0)

In [47]:
filter_drop = ['conta.contrato','conta.faturamente_eletronico','conta.metodo_pagamento']
data_normalized[filter_drop].isna().any(axis=1).sum()

np.int64(37)

In [ ]:
data_normalized = data_normalized.dropna(subset=filter_drop).copy()
data_normalized.reset_index(drop=True, inplace=True)
data_normalized.isna().sum()

id_cliente                       0
Churn                            0
cliente.genero                   0
cliente.idoso                    0
cliente.parceiro                 0
cliente.dependentes              0
cliente.tempo_servico            0
telefone.servico_telefone        0
telefone.varias_linhas           0
internet.servico_internet        0
internet.seguranca_online        0
internet.backup_online           0
internet.protecao_dispositivo    0
internet.suporte_tecnico         0
internet.tv_streaming            0
internet.filmes_streaming        0
conta.contrato                   0
conta.faturamente_eletronico     0
conta.metodo_pagamento           0
conta.cobranca.mensal            0
conta.cobranca.Total             0
dtype: int64

# Variáveis categóricas

In [59]:
data_normalized.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
1,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
2,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
3,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40
4,0013-MHZWF,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.4,571.45

In [ ]:
#Removendo dados de Id do cliente, já que são dispensáveis para dados de machine learning
data_normalized = data_normalized.drop('id_cliente', axis=1)
data_normalized.head()

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
1,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
2,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
3,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40
4,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.4,571.45

In [ ]:
#Consultando variavéis categoricas binárias
for col in data_normalized.columns:
    print(f'Coluna: {col}')
    print(data_normalized[col].unique())
    print('-'*30)

In [ ]:
#Realizando a substituição para dados binários
mapeamento = {
    'nao': 0,
    'sim': 1,
    'masculino': 0,
    'feminino': 1,
}
colunas = ['Churn', 'cliente.genero', 'cliente.parceiro', 'cliente.dependentes', 'telefone.servico_telefone', 'conta.faturamente_eletronico']

data_normalized[colunas] = data_normalized[colunas].replace(mapeamento)
data_normalized

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0,0,0,0,0,9.0,1,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,0,cheque pelo correio,59.90,542.40
1,1,0,0,0,0,4.0,1,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,1,cheque eletronico,73.90,280.85
2,1,0,1,1,0,13.0,1,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,1,cheque eletronico,98.00,1237.85
3,1,1,1,1,0,3.0,1,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,1,cheque pelo correio,83.90,267.40
4,0,1,0,0,1,9.0,1,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,1,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,0,1,0,0,0,13.0,1,nao,DSL,sim,nao,nao,sim,nao,nao,um ano,0,cheque pelo correio,55.15,742.90
7002,1,0,0,1,0,22.0,1,sim,fibra otica,nao,nao,nao,nao,nao,sim,mes a mes,1,cheque eletronico,85.10,1873.70
7003,0,0,0,0,0,2.0,1,nao,DSL,nao,sim,nao,nao,nao,nao,mes a mes,1,cheque pelo correio,50.30,92.75
7004,0,0,0,1,1,67.0,1,nao,DSL,sim,nao,sim,sim,nao,sim,dois anos,0,cheque pelo correio,67.85,4627.65
7005,0,0,0,1,1,63.0,0,sem servico de telefone,DSL,sim,sim,sim,nao,sim,sim,dois anos,0,cheque eletronico,59.00,3707.60

In [67]:
for col in data_normalized.columns:
    print(f'Coluna: {col}')
    print(data_normalized[col].unique())
    print('-'*30)

Coluna: Churn
[0 1]
------------------------------
Coluna: cliente.genero
[0 1]
------------------------------
Coluna: cliente.idoso
[0 1]
------------------------------
Coluna: cliente.parceiro
[0 1]
------------------------------
Coluna: cliente.dependentes
[0 1]
------------------------------
Coluna: cliente.tempo_servico
[9.00000000e+00 4.00000000e+00 1.30000000e+01 3.00000000e+00
 7.10000000e+01 6.30000000e+01 7.00000000e+00 6.58695412e+01
 5.40000000e+01 7.20000000e+01 5.00000000e+00 5.60000000e+01
 3.40000000e+01 1.00000000e+00 4.50000000e+01 5.00000000e+01
 2.30000000e+01 5.50000000e+01 2.60000000e+01 6.90000000e+01
 3.70000000e+01 4.90000000e+01 6.60000000e+01 6.70000000e+01
 2.00000000e+01 4.30000000e+01 5.90000000e+01 1.20000000e+01
 2.70000000e+01 2.00000000e+00 2.50000000e+01 2.90000000e+01
 1.40000000e+01 3.50000000e+01 6.40000000e+01 3.90000000e+01
 4.00000000e+01 1.10000000e+01 6.00000000e+00 3.00000000e+01
 7.00000000e+01 5.70000000e+01 5.80000000e+01 1.60000000e+01
 3.20000000e+01 3.30000000e+01 1.00000000e+01 2.10000000e+01
 6.10000000e+01 1.50000000e+01 4.40000000e+01 2.20000000e+01
 2.40000000e+01 1.90000000e+01 4.70000000e+01 6.20000000e+01
 4.60000000e+01 5.20000000e+01 8.00000000e+00 6.00000000e+01
 4.80000000e+01 2.80000000e+01 1.21467577e+01 4.97419859e+00
 4.10000000e+01 5.30000000e+01 6.80000000e+01 3.10000000e+01
 3.60000000e+01 1.70000000e+01 1.80000000e+01 6.50000000e+01
 5.10000000e+01 3.80000000e+01 4.20000000e+01 5.90920336e+01
 1.08000000e+03 1.00000000e+03 9.50000000e+02 2.54000000e+02
 3.21000000e+02 6.50000000e+02 7.21000000e+02 5.55000000e+02
 4.33000000e+02 5.12000000e+02 1.38607096e+01 5.66019417e+00
 4.84955992e+01 2.83627806e+01]
------------------------------
Coluna: telefone.servico_telefone
[1 0]
------------------------------
Coluna: telefone.varias_linhas
<StringArray>
['sim', 'nao', 'sem servico de telefone']
Length: 3, dtype: str
------------------------------
Coluna: internet.servico_internet
<StringArray>
['DSL', 'fibra otica', 'nao']
Length: 3, dtype: str
------------------------------
Coluna: internet.seguranca_online
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.backup_online
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.protecao_dispositivo
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.suporte_tecnico
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.tv_streaming
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.filmes_streaming
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: conta.contrato
<StringArray>
['mes a mes', 'dois anos', 'um ano']
Length: 3, dtype: str
------------------------------
Coluna: conta.faturamente_eletronico
[0 1]
------------------------------
Coluna: conta.metodo_pagamento
<StringArray>
[                'cheque pelo correio',                   'cheque eletronico',
      'cartao de credito (automatico)', 'transferencia bancaria (automatica)']
Length: 4, dtype: str
------------------------------
Coluna: conta.cobranca.mensal
[59.9  73.9  98.   ... 91.75 68.8  67.85]
------------------------------
Coluna: conta.cobranca.Total
[ 542.4   280.85 1237.85 ...  742.9  4627.65 3707.6 ]
------------------------------