In [1]:
import pandas as pd
import json

df = pd.read_json('../data/dataset-telecon.json')

In [2]:
df.head()

,id_cliente,Churn,cliente,telefone,internet,conta
0,0002-ORFBO,nao,"{'genero': 'feminino', 'idoso': 0, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': None, 'faturamente_eletronico': N..."
1,0003-MKNFE,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': 'mes a mes', 'faturamente_eletron..."
2,0004-TLHLJ,sim,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
3,0011-IGKFF,sim,"{'genero': 'masculino', 'idoso': 1, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
4,0013-EXCHZ,sim,"{'genero': 'feminino', 'idoso': 1, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  7344 non-null   str
 1   Churn       7344 non-null   str
 2   cliente     7344 non-null   object
 3   telefone    7344 non-null   object
 4   internet    7344 non-null   object
 5   conta       7344 non-null   object
dtypes: object(4), str(2)
memory usage: 344.4+ KB

## Normalizando colunas com formato JSON

In [4]:
with open('../data/dataset-telecon.json') as f:
    json_raw = json.load(f)
    
data_normalized = pd.json_normalize(json_raw)
data_normalized.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,NaN,NaN,NaN,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.4
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.4

In [5]:
data_normalized.info()

<class 'pandas.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   str
 1   Churn                          7344 non-null   str
 2   cliente.genero                 7344 non-null   str
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   str
 5   cliente.dependentes            7344 non-null   str
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   str
 8   telefone.varias_linhas         7344 non-null   str
 9   internet.servico_internet      7344 non-null   str
 10  internet.seguranca_online      7344 non-null   str
 11  internet.backup_online         7344 non-null   str
 12  internet.protecao_dispositivo  7344 non-null   str
 13  internet.suporte_tecnico       7344 non-null   str
 14  internet.tv_streaming          7344 non-null   str
 15  internet.filmes_streaming      7344 non-null   str
 16  conta.contrato                 7312 non-null   str
 17  conta.faturamente_eletronico   7326 non-null   str
 18  conta.metodo_pagamento         7317 non-null   str
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   str
dtypes: float64(2), int64(1), str(18)
memory usage: 1.2 MB

In [6]:
#data_normalized['conta.cobranca.Total'] = data_normalized['conta.cobranca.Total'].astype(float){}
#data_normalized[data_normalized['conta.cobranca.Total'] == ' '].head()
data_normalized['conta.cobranca.Total'] = data_normalized['conta.cobranca.Total'].astype(object)
data_normalized[data_normalized['conta.cobranca.Total'] == ' '][['cliente.tempo_servico','conta.contrato','conta.cobranca.mensal', 'conta.cobranca.Total']]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,0.0,dois anos,56.05,
1775,0.0,dois anos,20.00,
1955,0.0,dois anos,61.90,
2075,0.0,dois anos,19.70,
2232,0.0,dois anos,20.25,
2308,0.0,dois anos,25.35,
2930,0.0,dois anos,73.35,
3134,0.0,dois anos,25.75,
3203,0.0,dois anos,52.55,
4169,0.0,dois anos,80.85,
5599,0.0,dois anos,19.85,

In [7]:
idx = data_normalized[data_normalized['conta.cobranca.Total'] == ' '].index
data_normalized.loc[idx, 'cliente.tempo_servico'] = 24
data_normalized.loc[idx, 'conta.cobranca.Total'] = data_normalized.loc[idx,'cliente.tempo_servico'] * data_normalized.loc[idx,'conta.cobranca.mensal']
data_normalized.loc[idx, ['cliente.tempo_servico','conta.contrato','conta.cobranca.mensal', 'conta.cobranca.Total']]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,24.0,dois anos,56.05,1345.2
1775,24.0,dois anos,20.00,480.0
1955,24.0,dois anos,61.90,1485.6
2075,24.0,dois anos,19.70,472.8
2232,24.0,dois anos,20.25,486.0
2308,24.0,dois anos,25.35,608.4
2930,24.0,dois anos,73.35,1760.4
3134,24.0,dois anos,25.75,618.0
3203,24.0,dois anos,52.55,1261.2
4169,24.0,dois anos,80.85,1940.4
5599,24.0,dois anos,19.85,476.4

In [8]:
data_normalized['conta.cobranca.Total'] = data_normalized['conta.cobranca.Total'].astype(float)

# Identificando e tratando strings vazias

In [9]:
for col in data_normalized.columns:
    print(f'Coluna: {col}')
    print(data_normalized[col].unique())
    print('-' * 30)

Coluna: id_cliente
<StringArray>
['0002-ORFBO', '0003-MKNFE', '0004-TLHLJ', '0011-IGKFF', '0013-EXCHZ',
 '0013-MHZWF', '0013-SMEOE', '0014-BMAQU', '0015-UOCOJ', '0016-QLJIS',
 ...
 '9975-SKRNR', '9978-HYCIN', '9979-RGMZT', '9985-MWVIX', '9986-BONCE',
 '9987-LUTYD', '9992-RRAMN', '9992-UJOEL', '9993-LHIEB', '9995-HOTOH']
Length: 7267, dtype: str
------------------------------
Coluna: Churn
<StringArray>
['nao', 'sim', '']
Length: 3, dtype: str
------------------------------
Coluna: cliente.genero
<StringArray>
['feminino', 'masculino']
Length: 2, dtype: str
------------------------------
Coluna: cliente.idoso
[0 1]
------------------------------
Coluna: cliente.parceiro
<StringArray>
['sim', 'nao']
Length: 2, dtype: str
------------------------------
Coluna: cliente.dependentes
<StringArray>
['sim', 'nao']
Length: 2, dtype: str
------------------------------
Coluna: cliente.tempo_servico
[9.00e+00 4.00e+00 1.30e+01 3.00e+00 7.10e+01 6.30e+01 7.00e+00      nan
 5.40e+01 7.20e+01 5.00e+00 5.60e+01 3.40e+01 1.00e+00 4.50e+01 5.00e+01
 2.30e+01 5.50e+01 2.60e+01 6.90e+01 1.10e+01 3.70e+01 4.90e+01 6.60e+01
 6.70e+01 2.00e+01 4.30e+01 5.90e+01 1.20e+01 2.70e+01 2.00e+00 2.50e+01
 2.90e+01 1.40e+01 3.50e+01 6.40e+01 3.90e+01 4.00e+01 6.00e+00 3.00e+01
 7.00e+01 5.70e+01 5.80e+01 1.60e+01 3.20e+01 3.30e+01 1.00e+01 2.10e+01
 6.10e+01 1.50e+01 4.40e+01 2.20e+01 2.40e+01 1.90e+01 4.70e+01 6.20e+01
 4.60e+01 5.20e+01 8.00e+00 6.00e+01 4.80e+01 2.80e+01 6.50e+01 4.10e+01
 5.30e+01 6.80e+01 5.10e+01 3.10e+01 3.60e+01 1.70e+01 1.80e+01 3.80e+01
 4.20e+01 1.08e+03 1.00e+03 9.50e+02 2.54e+02 3.21e+02 6.50e+02 7.00e+02
 7.21e+02 5.55e+02 4.33e+02 5.12e+02]
------------------------------
Coluna: telefone.servico_telefone
<StringArray>
['sim', 'nao']
Length: 2, dtype: str
------------------------------
Coluna: telefone.varias_linhas
<StringArray>
['nao', 'sim', 'sem servico de telefone']
Length: 3, dtype: str
------------------------------
Coluna: internet.servico_internet
<StringArray>
['DSL', 'fibra otica', 'nao']
Length: 3, dtype: str
------------------------------
Coluna: internet.seguranca_online
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.backup_online
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.protecao_dispositivo
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.suporte_tecnico
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.tv_streaming
<StringArray>
['sim', 'nao', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: internet.filmes_streaming
<StringArray>
['nao', 'sim', 'sem servico de internet']
Length: 3, dtype: str
------------------------------
Coluna: conta.contrato
<StringArray>
[nan, 'mes a mes', 'dois anos', 'um ano']
Length: 4, dtype: str
------------------------------
Coluna: conta.faturamente_eletronico
<StringArray>
[nan, 'nao', 'sim']
Length: 3, dtype: str
------------------------------
Coluna: conta.metodo_pagamento
<StringArray>
[                                  nan,                 'cheque pelo correio',
                   'cheque eletronico',      'cartao de credito (automatico)',
 'transferencia bancaria (automatica)']
Length: 5, dtype: str
------------------------------
Coluna: conta.cobranca.mensal
[  nan 59.9  73.9  ... 91.75 68.8  67.85]
------------------------------
Coluna: conta.cobranca.Total
[    nan  542.4   280.85 ...  742.9  4627.65 3707.6 ]
------------------------------

In [10]:
data_normalized.query("Churn == ''")

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
30,0047-ZHDTW,,feminino,0,nao,nao,11.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,transferencia bancaria (automatica),79.00,929.30
75,0120-YZLQA,,masculino,0,nao,nao,71.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cartao de credito (automatico),19.90,1355.10
96,0154-QYHJU,,masculino,0,nao,nao,29.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,um ano,sim,cheque eletronico,58.75,1696.20
98,0162-RZGMZ,,feminino,1,nao,nao,5.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,mes a mes,nao,cartao de credito (automatico),59.90,287.85
175,0274-VVQOQ,,masculino,1,sim,nao,65.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,um ano,sim,transferencia bancaria (automatica),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7211,9920-GNDMB,,masculino,0,nao,nao,9.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,cheque eletronico,76.25,684.85
7239,9955-RVWSC,,feminino,0,sim,sim,67.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,transferencia bancaria (automatica),19.25,1372.90
7247,9966-VYRTZ,,feminino,0,sim,sim,31.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,mes a mes,sim,cheque pelo correio,19.55,658.95
7267,6532-YOHZY,,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,transferencia bancaria (automatica),109.75,4900.65
7342,3601-UTZXO,,masculino,0,sim,sim,41.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,transferencia bancaria (automatica),19.50,798.20

In [11]:
data_normalized = data_normalized[data_normalized['Churn'] != ''].copy().reset_index(drop=True, inplace=True)

In [ ]:
data_normalized = data_normalized[data_normalized['Churn'] != ''].copy().reset_index(drop=True)

AttributeError: 'NoneType' object has no attribute 'info'